export const initialProducts = [
  {
    id: 'brc-keyring-01',
    name: 'Pink Bloom Keyring',
    price: 159,
    category: 'พวงกุญแจ',
    description: 'พวงกุญแจลูกปัดโทนชมพูหวาน แต่งดอกไม้เล็กๆ เหมาะกับกระเป๋าใบโปรด',
    badge: 'Best Seller',
    imageUrl: '',
    isFeatured: true,
    isVisible: true,
    sortOrder: 1,
  },
  {
    id: 'brc-necklace-01',
    name: 'Milky Bead Necklace',
    price: 249,
    category: 'สร้อยลูกปัด',
    description: 'สร้อยลูกปัดโทนน้ำนมกับชมพูใส ใส่เดี่ยวก็น่ารัก เลเยอร์ก็ดูสดใส',
    badge: 'New',
    imageUrl: '',
    isFeatured: true,
    isVisible: true,
    sortOrder: 2,
  },
  {
    id: 'brc-custom-01',
    name: 'Custom Name Charm',
    price: 189,
    category: 'Custom Order',
    description: 'เลือกชื่อ สี และโทนลูกปัดได้ เหมาะเป็นของขวัญวันเกิดหรือของคู่กัน',
    badge: 'Custom',
    imageUrl: '',
    isFeatured: true,
    isVisible: true,
    sortOrder: 3,
  },
  {
    id: 'brc-bag-01',
    name: 'Candy Bag Charm',
    price: 179,
    category: 'Bag Charm',
    description: 'ชาร์มห้อยกระเป๋าโทนลูกกวาด สีพาสเทลสดใส ถ่ายรูปขึ้นมาก',
    badge: 'Cute Pick',
    imageUrl: '',
    isFeatured: false,
    isVisible: true,
    sortOrder: 4,
  },
  {
    id: 'brc-phone-01',
    name: 'Berry Phone Strap',
    price: 139,
    category: 'Phone Strap',
    description: 'สายคล้องมือถือทรงเบอร์รี่จิ๋ว น้ำหนักเบา ใช้ได้ทุกวัน',
    badge: 'Ready',
    imageUrl: '',
    isFeatured: false,
    isVisible: true,
    sortOrder: 5,
  },
  {
    id: 'brc-gift-01',
    name: 'Mini Gift Set',
    price: 299,
    category: 'Gift Set',
    description: 'เซ็ตของขวัญ handmade พร้อมแพ็กเกจหวานๆ สำหรับคนพิเศษ',
    badge: 'Gift',
    imageUrl: '',
    isFeatured: true,
    isVisible: true,
    sortOrder: 6,
  },
];

export const initialSettings = {
  instagramUrl: 'https://www.instagram.com/thebrinc.c/',
  tiktokUrl: 'https://www.tiktok.com/@thebrinc.c?is_from_webapp=1&sender_device=pc',
  shopeeUrl:
    'https://shopee.co.th/thebrinc.c?categoryId=100639&entryPoint=ShopByPDP&itemId=27774579058',
  lineUrl: '#',
  announcement: 'Custom order เปิดรับตามคิวค่ะ',
};

export const categories = [
  'ทั้งหมด',
  'พวงกุญแจ',
  'สร้อยลูกปัด',
  'Best Seller',
  'Custom Order',
  'Gift Set',
];
